"""add skill column to votes

Revision ID: 2ee8f15a9299
Revises: 837fedc709bd
Create Date: 2024-04-03 14:54:16.227422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee8f15a9299'
down_revision: Union[str, None] = '837fedc709bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('skill', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'skill')
    # ### end Alembic commands ###
