"""add auth

Revision ID: 15d9b4e8dd35
Revises: b739c42f28fd
Create Date: 2024-03-20 14:56:34.241681

"""
from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d9b4e8dd35'
down_revision: Union[str, None] = 'b739c42f28fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('justify', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('skill', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'user_id', 'id')
    )
    op.add_column('user', sa.Column('email', sa.String(length=320), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_index('ix_user_account_id', table_name='user')
    op.drop_index('ix_user_oauth_name', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_constraint('user_user_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'account_email')
    op.drop_column('user', 'account_id')
    op.drop_column('user', 'expires_at')
    op.drop_column('user', 'user_id')
    op.drop_column('user', 'oauth_name')
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('oauth_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('account_id', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('account_email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('refresh_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.create_foreign_key('user_user_id_fkey', 'user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_oauth_name', 'user', ['oauth_name'], unique=False)
    op.create_index('ix_user_account_id', 'user', ['account_id'], unique=False)
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'email')
    op.drop_table('votes')
    # ### end Alembic commands ###
