"""add export table

Revision ID: 2e7ba1d81542
Revises: f19d1b0e640a
Create Date: 2024-03-14 21:11:32.572911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7ba1d81542'
down_revision: Union[str, None] = 'f19d1b0e640a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_owners',
    sa.Column('car_number', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('tg', sa.String(), nullable=True),
    sa.Column('vk', sa.String(), nullable=True),
    sa.Column('ID', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('car_number')
    )
    op.create_table('violations',
    sa.Column('violation_type', sa.String(), nullable=False),
    sa.Column('fine', sa.Float(), nullable=False),
    sa.Column('ID', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('violation_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violations')
    op.drop_table('car_owners')
    # ### end Alembic commands ###
