"""add photo_id column

Revision ID: 3df6d22ee971
Revises: a1688956afa8
Create Date: 2024-03-17 21:30:10.725445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df6d22ee971'
down_revision: Union[str, None] = 'a1688956afa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('photo_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'cases', 'files', ['photo_id'], ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'photo_id')
    # ### end Alembic commands ###
