"""add cases table

Revision ID: 4f7eed1ec012
Revises: f15e62f6426d
Create Date: 2024-03-16 22:30:41.958259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7eed1ec012'
down_revision: Union[str, None] = 'f15e62f6426d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('transport', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('violation_id', sa.Uuid(), nullable=False),
    sa.Column('violation_value', sa.String(), nullable=False),
    sa.Column('skill_value', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('ID', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.ID'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['car_owners.ID'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cases')
    # ### end Alembic commands ###
