"""add vote columns

Revision ID: 837fedc709bd
Revises: 89ef56dde1f0
Create Date: 2024-03-21 00:55:35.410300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837fedc709bd'
down_revision: Union[str, None] = '89ef56dde1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('justify', sa.Boolean(), nullable=True))
    op.add_column('votes', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'timestamp')
    op.drop_column('votes', 'justify')
    # ### end Alembic commands ###
