"""refactor votes table

Revision ID: ad225138ca6d
Revises: 15d9b4e8dd35
Create Date: 2024-03-20 20:40:06.285564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad225138ca6d'
down_revision: Union[str, None] = '15d9b4e8dd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'justify',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('votes', 'skill')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('skill', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('votes', 'justify',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
