"""update cases table

Revision ID: c01b37a276c7
Revises: 4f7eed1ec012
Create Date: 2024-03-16 22:54:13.973863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c01b37a276c7'
down_revision: Union[str, None] = '4f7eed1ec012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_timestamp', sa.DateTime(), nullable=False))
    op.add_column('cases', sa.Column('status', sa.String(), nullable=False))
    op.add_column('cases', sa.Column('status_timestamp', sa.DateTime(), nullable=False))
    op.add_column('cases', sa.Column('justify_votes_count', sa.Integer(), nullable=False))
    op.add_column('cases', sa.Column('convict_votes_count', sa.Integer(), nullable=False))
    op.drop_column('cases', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('cases', 'convict_votes_count')
    op.drop_column('cases', 'justify_votes_count')
    op.drop_column('cases', 'status_timestamp')
    op.drop_column('cases', 'status')
    op.drop_column('cases', 'case_timestamp')
    # ### end Alembic commands ###
