"""Database creation

Revision ID: d7a8d1cc70ee
Revises: 
Create Date: 2024-03-11 16:07:21.041363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a8d1cc70ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependencies',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('enclosure', sa.Uuid(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('field_attrs', sa.JSON(), nullable=False),
    sa.Column('ID', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['enclosure'], ['dependencies.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependencies')
    # ### end Alembic commands ###
