"""add cameras table

Revision ID: f19d1b0e640a
Revises: d7a8d1cc70ee
Create Date: 2024-03-13 15:20:25.920456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19d1b0e640a'
down_revision: Union[str, None] = 'd7a8d1cc70ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cam_type', sa.Uuid(), nullable=False),
    sa.Column('ID', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cam_type'], ['dependencies.ID'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cameras')
    # ### end Alembic commands ###
