"""add users table

Revision ID: fdd7ef1614c0
Revises: 3df6d22ee971
Create Date: 2024-03-18 10:22:25.325053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd7ef1614c0'
down_revision: Union[str, None] = '3df6d22ee971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('wallet', sa.Float(), nullable=False),
    sa.Column('ID', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('votes',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('justify', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('skill', sa.Integer(), nullable=False),
    sa.Column('ID', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.ID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.ID'], ),
    sa.PrimaryKeyConstraint('case_id', 'user_id', 'ID')
    )
    op.drop_column('cases', 'convict_votes_count')
    op.drop_column('cases', 'justify_votes_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('justify_votes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cases', sa.Column('convict_votes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('votes')
    op.drop_table('users')
    # ### end Alembic commands ###
